[package]
name = "streamshield"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
base64 = "0.22"
image = { version = "0.25", default-features = false, features = ["png"] }
tungstenite = { version = "0.21", default-features = false, features = ["handshake"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [
  "winuser", "processthreadsapi", "psapi",
  "handleapi", "errhandlingapi", "winnt",
  "shellapi", "securitybaseapi",
  "memoryapi", "libloaderapi", "synchapi",
  "winerror", "minwindef", "basetsd",
  "tlhelp32", "wingdi", "dwmapi",
  "combaseapi", "objbase", "unknwnbase", "guiddef",
] }
